### PR TITLE
create doc folder

### PR DESCRIPTION
**Pull request by PelerYuan**
一些开发文件暂时写在这里吧

### CODE REVIEW

**Comment by Tommy-Zhang3759** [comment]
it the branch still necessary? if not, i would delete it

**Comment by PelerYuan** [comment]
No, all the docs about this project are at https://www.blog.peler.top/categories/SysyncWin-%E5%BC%80%E5%8F%91%E8%B8%A9%E5%9D%91%E6%97%A5%E8%AE%B0/

**Comment by Tommy-Zhang3759** [comment]
if not, please delete the doc branch

**Comment by PelerYuan** [comment]
Got it

**Pull request closed without merging**
